
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Entry txtVaprox;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Entry txtErel;

	private global::Gtk.Label label8;

	private global::Gtk.Button btnCalcular;

	private global::Gtk.Button btnSalir;

	private global::Gtk.Entry txtVtrue;

	private global::Gtk.Entry txtEabs;

	private global::Gtk.Entry txtErp;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calcular error");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Introduce el valor verdadero");
		this.fixed2.Add(this.label3);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
		w1.X = 22;
		w1.Y = 21;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Introduce el valor aproximado");
		this.fixed2.Add(this.label4);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label4]));
		w2.X = 241;
		w2.Y = 20;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtVaprox = new global::Gtk.Entry();
		this.txtVaprox.CanFocus = true;
		this.txtVaprox.Name = "txtVaprox";
		this.txtVaprox.IsEditable = true;
		this.txtVaprox.InvisibleChar = '•';
		this.fixed2.Add(this.txtVaprox);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtVaprox]));
		w3.X = 242;
		w3.Y = 57;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Resultados");
		this.fixed2.Add(this.label5);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
		w4.X = 22;
		w4.Y = 112;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Error absoluto");
		this.fixed2.Add(this.label6);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
		w5.X = 28;
		w5.Y = 150;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Error relativo");
		this.fixed2.Add(this.label7);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label7]));
		w6.X = 31;
		w6.Y = 187;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtErel = new global::Gtk.Entry();
		this.txtErel.CanFocus = true;
		this.txtErel.Name = "txtErel";
		this.txtErel.IsEditable = true;
		this.txtErel.InvisibleChar = '•';
		this.fixed2.Add(this.txtErel);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtErel]));
		w7.X = 148;
		w7.Y = 183;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Error relativo porcentual");
		this.fixed2.Add(this.label8);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label8]));
		w8.X = 32;
		w8.Y = 234;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnCalcular = new global::Gtk.Button();
		this.btnCalcular.CanFocus = true;
		this.btnCalcular.Name = "btnCalcular";
		this.btnCalcular.UseUnderline = true;
		this.btnCalcular.Label = global::Mono.Unix.Catalog.GetString("Calcular");
		this.fixed2.Add(this.btnCalcular);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnCalcular]));
		w9.X = 92;
		w9.Y = 304;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnSalir = new global::Gtk.Button();
		this.btnSalir.CanFocus = true;
		this.btnSalir.Name = "btnSalir";
		this.btnSalir.UseUnderline = true;
		this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.fixed2.Add(this.btnSalir);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnSalir]));
		w10.X = 275;
		w10.Y = 301;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtVtrue = new global::Gtk.Entry();
		this.txtVtrue.CanFocus = true;
		this.txtVtrue.Name = "txtVtrue";
		this.txtVtrue.IsEditable = true;
		this.txtVtrue.InvisibleChar = '•';
		this.fixed2.Add(this.txtVtrue);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtVtrue]));
		w11.X = 25;
		w11.Y = 51;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtEabs = new global::Gtk.Entry();
		this.txtEabs.CanFocus = true;
		this.txtEabs.Name = "txtEabs";
		this.txtEabs.IsEditable = false;
		this.txtEabs.InvisibleChar = '•';
		this.fixed2.Add(this.txtEabs);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtEabs]));
		w12.X = 148;
		w12.Y = 133;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txtErp = new global::Gtk.Entry();
		this.txtErp.CanFocus = true;
		this.txtErp.Name = "txtErp";
		this.txtErp.IsEditable = true;
		this.txtErp.InvisibleChar = '•';
		this.fixed2.Add(this.txtErp);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtErp]));
		w13.X = 227;
		w13.Y = 231;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 479;
		this.DefaultHeight = 361;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnCalcular.Clicked += new global::System.EventHandler(this.OnBtnCalcularClicked);
		this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
	}
}
