
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView Tabla;

	private global::Gtk.Label GtkLabel2;

	private global::Gtk.Table table3;

	private global::Gtk.Label label3;

	private global::Gtk.Entry txtFuncion;

	private global::Gtk.Button btnLimpiar;

	private global::Gtk.Button button2;

	private global::Gtk.Table table4;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button1;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.Table table2;

	private global::Gtk.RadioButton rdbEs;

	private global::Gtk.RadioButton rdbLimite;

	private global::Gtk.Entry txtEs;

	private global::Gtk.Entry txtLimite;

	private global::Gtk.Label GtkLabel9;

	private global::Gtk.Table table1;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label4;

	private global::Gtk.Entry txtVVerdadero;

	private global::Gtk.Entry txtXl;

	private global::Gtk.Entry txtXu;

	private global::Gtk.Button btnPrueba;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Metodo Falsa Posicion");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.WidthRequest = 700;
		this.frame2.HeightRequest = 200;
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Tabla = new global::Gtk.TreeView();
		this.Tabla.WidthRequest = 100;
		this.Tabla.CanFocus = true;
		this.Tabla.Name = "Tabla";
		this.GtkScrolledWindow.Add(this.Tabla);
		this.GtkAlignment.Add(this.GtkScrolledWindow);
		this.frame2.Add(this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Tabla de resultados</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel2;
		this.fixed1.Add(this.frame2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame2]));
		w5.X = 11;
		w5.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table3 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Funcion:  f(x)=  ");
		this.table3.Add(this.label3);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.label3]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.txtFuncion = new global::Gtk.Entry();
		this.txtFuncion.WidthRequest = 300;
		this.txtFuncion.CanFocus = true;
		this.txtFuncion.Name = "txtFuncion";
		this.txtFuncion.Text = global::Mono.Unix.Catalog.GetString("(667.38/x)*(1-exp(-0.146843*x))-40");
		this.txtFuncion.IsEditable = true;
		this.txtFuncion.InvisibleChar = '•';
		this.table3.Add(this.txtFuncion);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.txtFuncion]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add(this.table3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.table3]));
		w8.X = 17;
		w8.Y = 9;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLimpiar = new global::Gtk.Button();
		this.btnLimpiar.CanFocus = true;
		this.btnLimpiar.Name = "btnLimpiar";
		this.btnLimpiar.UseUnderline = true;
		this.btnLimpiar.Label = global::Mono.Unix.Catalog.GetString("Limpiar");
		this.fixed1.Add(this.btnLimpiar);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnLimpiar]));
		w9.X = 271;
		w9.Y = 189;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w10.X = 367;
		w10.Y = 189;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table4 = new global::Gtk.Table(((uint)(1)), ((uint)(6)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.HeightRequest = 40;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("^");
		this.table4.Add(this.button3);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4[this.button3]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.HeightRequest = 40;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = "e";
		this.table4.Add(this.button4);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4[this.button4]));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add(this.table4);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.table4]));
		w13.X = 445;
		w13.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Calcular");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w14.X = 178;
		w14.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table(((uint)(1)), ((uint)(6)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.rdbEs = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("(Ea<Es) Es:"));
		this.rdbEs.CanFocus = true;
		this.rdbEs.Name = "rdbEs";
		this.rdbEs.Active = true;
		this.rdbEs.DrawIndicator = true;
		this.rdbEs.UseUnderline = true;
		this.rdbEs.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.table2.Add(this.rdbEs);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.rdbEs]));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.rdbLimite = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Limite de iteraciones:"));
		this.rdbLimite.CanFocus = true;
		this.rdbLimite.Name = "rdbLimite";
		this.rdbLimite.DrawIndicator = true;
		this.rdbLimite.UseUnderline = true;
		this.rdbLimite.Group = this.rdbEs.Group;
		this.table2.Add(this.rdbLimite);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2[this.rdbLimite]));
		w16.LeftAttach = ((uint)(2));
		w16.RightAttach = ((uint)(3));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtEs = new global::Gtk.Entry();
		this.txtEs.WidthRequest = 50;
		this.txtEs.CanFocus = true;
		this.txtEs.Name = "txtEs";
		this.txtEs.IsEditable = true;
		this.txtEs.InvisibleChar = '•';
		this.table2.Add(this.txtEs);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2[this.txtEs]));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtLimite = new global::Gtk.Entry();
		this.txtLimite.WidthRequest = 50;
		this.txtLimite.CanFocus = true;
		this.txtLimite.Name = "txtLimite";
		this.txtLimite.IsEditable = false;
		this.txtLimite.InvisibleChar = '•';
		this.table2.Add(this.txtLimite);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2[this.txtLimite]));
		w18.LeftAttach = ((uint)(3));
		w18.RightAttach = ((uint)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add(this.table2);
		this.frame3.Add(this.GtkAlignment1);
		this.GtkLabel9 = new global::Gtk.Label();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Formas de terminar:</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel9;
		this.fixed1.Add(this.frame3);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame3]));
		w21.X = 33;
		w21.Y = 104;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(6)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Valor inferior(Xl): ");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Valor Superior(Xu): ");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w23.LeftAttach = ((uint)(2));
		w23.RightAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Valor Verdadero");
		this.table1.Add(this.label4);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
		w24.LeftAttach = ((uint)(4));
		w24.RightAttach = ((uint)(5));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtVVerdadero = new global::Gtk.Entry();
		this.txtVVerdadero.WidthRequest = 90;
		this.txtVVerdadero.CanFocus = true;
		this.txtVVerdadero.Name = "txtVVerdadero";
		this.txtVVerdadero.Text = global::Mono.Unix.Catalog.GetString("14.7802");
		this.txtVVerdadero.IsEditable = true;
		this.txtVVerdadero.InvisibleChar = '•';
		this.table1.Add(this.txtVVerdadero);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.txtVVerdadero]));
		w25.LeftAttach = ((uint)(5));
		w25.RightAttach = ((uint)(6));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtXl = new global::Gtk.Entry();
		this.txtXl.WidthRequest = 70;
		this.txtXl.CanFocus = true;
		this.txtXl.Name = "txtXl";
		this.txtXl.IsEditable = true;
		this.txtXl.InvisibleChar = '•';
		this.table1.Add(this.txtXl);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.txtXl]));
		w26.LeftAttach = ((uint)(1));
		w26.RightAttach = ((uint)(2));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtXu = new global::Gtk.Entry();
		this.txtXu.WidthRequest = 70;
		this.txtXu.CanFocus = true;
		this.txtXu.Name = "txtXu";
		this.txtXu.IsEditable = true;
		this.txtXu.InvisibleChar = '•';
		this.table1.Add(this.txtXu);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.txtXu]));
		w27.LeftAttach = ((uint)(3));
		w27.RightAttach = ((uint)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add(this.table1);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.table1]));
		w28.X = 32;
		w28.Y = 56;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnPrueba = new global::Gtk.Button();
		this.btnPrueba.CanFocus = true;
		this.btnPrueba.Name = "btnPrueba";
		this.btnPrueba.UseUnderline = true;
		this.btnPrueba.Label = global::Mono.Unix.Catalog.GetString("Prueba");
		this.fixed1.Add(this.btnPrueba);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnPrueba]));
		w29.X = 523;
		w29.Y = 105;
		w1.Add(this.fixed1);
		this.scrolledwindow1.Add(w1);
		this.Add(this.scrolledwindow1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 726;
		this.DefaultHeight = 350;
		this.btnPrueba.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnLimpiar.Clicked += new global::System.EventHandler(this.LimpiarButton);
		this.button2.Clicked += new global::System.EventHandler(this.SalirClick);
		this.button4.Clicked += new global::System.EventHandler(this.Signoe);
		this.button3.Clicked += new global::System.EventHandler(this.AgregarSigno1);
		this.button1.Clicked += new global::System.EventHandler(this.CalcularSalir);
		this.rdbLimite.Clicked += new global::System.EventHandler(this.LimiteChanged);
		this.rdbEs.Clicked += new global::System.EventHandler(this.EsChanged);
		this.btnPrueba.Clicked += new global::System.EventHandler(this.Prueba);
	}
}
